### PR TITLE
RoR-Active record.

### PR DESCRIPTION
**Pull request by SigmaSam**
### Created three tables for content:
- One for User data.
- One for Posts data.
- One for Comments data.

### Defined the relations between tables:
- Users has many posts and comments.
- Post belongs to users has many comments.
- Comments belong to Post and  User.

### Set validations for length, and presence for the data input.

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
**Hi Team 👋**

**You both did pretty well on this. 👌**

However:

- [x] Its not necessary to sign in the user with a password in this project. Simply use the attributes of `username` and 'email` to sign in the user. Therefore, replace the `name` attribute on the user model with a `username` attribute instead and remove the `password` field.

- [x] Kindly add validations on comments for the presence of the comment `body` attribute.

- [x] Your `Comments` association seems to be returning an `ActiveRecord::Associations::CollectionProxy`, it should rather return an `ActiveRecord::AssociationRelation` so that this: `Users.first.comments.length` would return the right value. Consider fixing this.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Progress @team :clap: However, some changes need to be applied in order to get approval for this project. Check :arrow_down: 

#### General required :warning: 
* [x] Add /node_modules and all unnecessary files to .gitignore. The repository size is so big :red_circle: 
#### Implementation (required) :warning: 
* [x] Your Comments association seems to be returning an ActiveRecord::Associations::CollectionProxy, it should rather return an ActiveRecord::AssociationRelation so that this: Users.first.comments.length would return the right value. Consider fixing this.
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello :wave:, well done on your progress :clap:**

- We still don't have node_modules included in .gitignore as requested previously. Please take care of this. SInce node_modules is already being tracked by git, check [here](https://stackoverflow.com/a/1274447) for how to stop tracking it.

Please take care of the above and submit another code review request.

### Status: Changes required

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, great job on this project :+1: Having fixed all the comments outlined by the previous TSE's :smile: I hereby approve of your project :fireworks: Congratulations :1st_place_medal: 

Go ahead and merge into development :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
